#!/bin/bash
export KERNEL=kernel7l
export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabihf-

mkdir -p ~/boot-rpi/overlays
mkdir -p ~/modules-rpi
cd linux
make INSTALL_MOD_PATH=~/modules-rpi modules_install
cp arch/arm/boot/zImage ~/boot-rpi/$KERNEL.img
cp arch/arm/boot/dts/overlays/*.dtb ~/boot-rpi/
cp arch/arm/boot/dts/overlays/*.dtb* ~/boot-rpi/overlays/
cp arch/arm/boot/dts/overlays/README ~/boot-rpi/overlays/
# This line is needed for the out of tree builds.
make modules
